name: debt_manager
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  get: ^4.6.6
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.0+1
  cookie_jar: ^4.0.8
  font_awesome_flutter: ^10.2.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  google_sign_in: ^6.2.1
  awesome_dialog: ^3.1.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/sound/