name: debt_manager
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.1
  firebase_analytics: ^11.3.2
  get: ^4.6.6
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.0+1
  cookie_jar: ^4.0.8
  font_awesome_flutter: ^10.2.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  awesome_dialog: ^3.1.0
  crypto: ^3.0.1
  image_picker: ^1.1.2
  http: ^0.13.5
  path_provider: ^2.1.1
  mobile_scanner: ^6.0.1


  cupertino_icons: ^1.0.2
  firebase_app_check: ^0.3.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/sound/